"""sync_models_and_onboarding

Revision ID: 10afa46b8d8a
Revises: e274c21a9d65
Create Date: 2026-04-16 15:27:43.408657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10afa46b8d8a'
down_revision: Union[str, Sequence[str], None] = 'e274c21a9d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
