"""add_onboarding_tasks_table

Revision ID: 1ed8a42632d5
Revises: 7064cd011618
Create Date: 2026-04-15 11:53:38.968163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ed8a42632d5'
down_revision: Union[str, Sequence[str], None] = '7064cd011618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_tasks', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.add_column('onboarding_tasks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('onboarding_tasks', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('onboarding_tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('onboarding_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'onboarding_tasks', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'onboarding_tasks', type_='foreignkey')
    op.alter_column('onboarding_tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('onboarding_tasks', 'completed_at')
    op.drop_column('onboarding_tasks', 'due_date')
    op.drop_column('onboarding_tasks', 'is_completed')
    op.drop_column('onboarding_tasks', 'employee_id')
    # ### end Alembic commands ###
