"""fix_onboarding_models_and_cleanup

Revision ID: e274c21a9d65
Revises: 0a1c40ff2581
Create Date: 2026-04-15 12:16:38.142441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e274c21a9d65'
down_revision: Union[str, Sequence[str], None] = '0a1c40ff2581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_onboarding_id', table_name='employee_onboarding')
    op.drop_table('employee_onboarding')
    op.alter_column('onboarding_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('onboarding_tasks', 'category')
    op.drop_column('onboarding_tasks', 'is_mandatory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_tasks', sa.Column('is_mandatory', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('onboarding_tasks', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('onboarding_tasks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('employee_onboarding',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_onboarding_employee_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['onboarding_tasks.id'], name='employee_onboarding_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employee_onboarding_pkey')
    )
    op.create_index('ix_employee_onboarding_id', 'employee_onboarding', ['id'], unique=False)
    # ### end Alembic commands ###
